In [1]:
%pip install datasets
%pip install pandas

Collecting datasets
  Downloading datasets-4.5.0-py3-none-any.whl (515 kB)
     |████████████████████████████████| 515 kB 896 kB/s eta 0:00:01
Requirement already satisfied: pyyaml>=5.1 in ./.venv/lib/python3.9/site-packages (from datasets) (6.0.3)
Collecting pyarrow>=21.0.0
  Using cached pyarrow-21.0.0-cp39-cp39-macosx_12_0_arm64.whl (31.2 MB)
Collecting multiprocess<0.70.19
  Using cached multiprocess-0.70.18-py39-none-any.whl (133 kB)
Requirement already satisfied: pandas in ./.venv/lib/python3.9/site-packages (from datasets) (2.3.3)
Requirement already satisfied: filelock in ./.venv/lib/python3.9/site-packages (from datasets) (3.19.1)
Collecting dill<0.4.1,>=0.3.0
  Using cached dill-0.4.0-py3-none-any.whl (119 kB)
Requirement already satisfied: httpx<1.0.0 in ./.venv/lib/python3.9/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in ./.venv/lib/python3.9/site-packages (from datasets) (4.67.1)
Collecting xxhash
  Using cached xxhash-3.6.0-cp39-cp39-macosx_11_0_arm64.whl (30 kB)
Requirement already satisfied: numpy>=1.17 in ./.venv/lib/python3.9/site-packages (from datasets) (2.0.2)
Requirement already satisfied: requests>=2.32.2 in ./.venv/lib/python3.9/site-packages (from datasets) (2.32.5)
Requirement already satisfied: fsspec[http]<=2025.10.0,>=2023.1.0 in ./.venv/lib/python3.9/site-packages (from datasets) (2025.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in ./.venv/lib/python3.9/site-packages (from datasets) (0.36.0)
Requirement already satisfied: packaging in ./.venv/lib/python3.9/site-packages (from datasets) (25.0)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1
  Downloading aiohttp-3.13.3-cp39-cp39-macosx_11_0_arm64.whl (492 kB)
     |████████████████████████████████| 492 kB 863 kB/s eta 0:00:01
Collecting yarl<2.0,>=1.17.0
  Using cached yarl-1.22.0-cp39-cp39-macosx_11_0_arm64.whl (94 kB)
Requirement already satisfied: attrs>=17.3.0 in ./.venv/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Collecting aiosignal>=1.4.0
  Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.7.1-cp39-cp39-macosx_11_0_arm64.whl (44 kB)
     |████████████████████████████████| 44 kB 929 kB/s eta 0:00:01
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.8.0-cp39-cp39-macosx_11_0_arm64.whl (50 kB)
Collecting aiohappyeyeballs>=2.5.0
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Collecting propcache>=0.2.0
  Using cached propcache-0.4.1-cp39-cp39-macosx_11_0_arm64.whl (47 kB)
Collecting async-timeout<6.0,>=4.0
  Using cached async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Requirement already satisfied: typing-extensions>=4.2 in ./.venv/lib/python3.9/site-packages (from aiosignal>=1.4.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (4.15.0)
Requirement already satisfied: certifi in ./.venv/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (2025.11.12)
Requirement already satisfied: idna in ./.venv/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: anyio in ./.venv/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (4.11.0)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.9/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./.venv/lib/python3.9/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.9/site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.9/site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in ./.venv/lib/python3.9/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in ./.venv/lib/python3.9/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.9/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.9/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.9/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Installing collected packages: propcache, multidict, frozenlist, yarl, async-timeout, aiosignal, aiohappyeyeballs, dill, aiohttp, xxhash, pyarrow, multiprocess, datasets
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.3 aiosignal-1.4.0 async-timeout-5.0.1 datasets-4.5.0 dill-0.4.0 frozenlist-1.8.0 multidict-6.7.1 multiprocess-0.70.18 propcache-0.4.1 pyarrow-21.0.0 xxhash-3.6.0 yarl-1.22.0
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/nirashanelki/Documents/Works/Research/codes/factual_inconsistency_validate_xai/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in ./.venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: numpy>=1.22.4 in ./.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/nirashanelki/Documents/Works/Research/codes/factual_inconsistency_validate_xai/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [1]:
from datasets import load_dataset

ds = load_dataset("nkwbtb/SummaCoz")

/Users/nirashanelki/Documents/Works/Research/codes/factual_inconsistency_validate_xai/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/nirashanelki/Documents/Works/Research/codes/factual_inconsistency_validate_xai/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import pandas as pd

data = ds['train']
data_df = pd.DataFrame(data)

data_df = data_df[(data_df['reason'] != '') & (data_df['origin'] == 'cnndm')]
data_df.head()


# save the dataframe to a CSV file
data_df.to_csv('data/summcoz_train_cnndm.csv', index=False)

In [3]:
len(data_df)

724

In [14]:
new_df = pd.DataFrame()

for idx, row in data_df.iterrows():
    if idx % 3 == 0:
        new_df = pd.concat([new_df, row.to_frame().T], ignore_index=True)

In [15]:
new_df[90:100]

,summary,article,reason,origin,dataset,label
90,"jacqueline crane, 52, pretended to be a profes...",Jacqueline Crane (pictured outside court) clai...,"1. The summary states jacqueline crane, 52, pr...",cnndm,cogensumm,2
91,"jacqueline crane, 52, pretended to be a profes...",Jacqueline Crane (pictured outside court) clai...,"1. The summary says jacqueline crane, 52, pret...",cnndm,cogensumm,2
92,taylor swift has been a star since the age of ...,Taylor Swift has been a star since the age of ...,1. The summary states that Taylor Swift has 52...,cnndm,cogensumm,2
93,taylor swift has been a fan since the age of 1...,Taylor Swift has been a star since the age of ...,1. The summary states taylor swift has been a ...,cnndm,cogensumm,2
94,taylor swift has been a star since the age of ...,Taylor Swift has been a star since the age of ...,1. The summary claims the 25 year old from pen...,cnndm,cogensumm,2
95,stuart pearce believes gary neville needs to g...,Stuart Pearce believes Gary Neville needs to g...,1. The summary states that Stuart Pearce belie...,cnndm,cogensumm,2
96,stuart pearce believes gary neville needs to g...,Stuart Pearce believes Gary Neville needs to g...,1. The summary states neville has been in char...,cnndm,cogensumm,2
97,stuart pearce believes gary neville needs to g...,Stuart Pearce believes Gary Neville needs to g...,1. The summary claims neville has been tipped ...,cnndm,cogensumm,2
98,stuart pearce says neville needs to get manage...,Stuart Pearce believes Gary Neville needs to g...,1. The summary states neville has been tipped ...,cnndm,cogensumm,2
99,the double world champion has chosen shrewdly ...,Being in the right place at the right time is ...,1. The summary claims hamilton says his new me...,cnndm,cogensumm,2

In [16]:
filtered_data_df = new_df[:100]

# save the filtered dataframe to a new CSV file
filtered_data_df.to_csv('data/hallucination_test/summcoz_train_sample_100.csv')

In [7]:
filtered_data_df = pd.read_csv('data/hallucination_test/summcoz_train_sample_100.csv')
filtered_data_df.tail()

,id,summary,article,reason,origin,dataset,label
95,95,stuart pearce believes gary neville needs to g...,Stuart Pearce believes Gary Neville needs to g...,1. The summary states that Stuart Pearce belie...,cnndm,cogensumm,2
96,96,stuart pearce believes gary neville needs to g...,Stuart Pearce believes Gary Neville needs to g...,1. The summary states neville has been in char...,cnndm,cogensumm,2
97,97,stuart pearce believes gary neville needs to g...,Stuart Pearce believes Gary Neville needs to g...,1. The summary claims neville has been tipped ...,cnndm,cogensumm,2
98,98,stuart pearce says neville needs to get manage...,Stuart Pearce believes Gary Neville needs to g...,1. The summary states neville has been tipped ...,cnndm,cogensumm,2
99,99,the double world champion has chosen shrewdly ...,Being in the right place at the right time is ...,1. The summary claims hamilton says his new me...,cnndm,cogensumm,2

In [9]:
filtered_data_df = pd.concat([filtered_data_df, new_df[100:110]], ignore_index=True)

In [13]:
filtered_data_df.to_csv('data/hallucination_test/summcoz_train_sample_100.csv', index=False)