In [ ]:
pip install unsloth peft transformers accelerate torch

Collecting unsloth
  Downloading unsloth-2026.4.6-py3-none-any.whl.metadata (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 kB 5.1 MB/s eta 0:00:00
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Collecting unsloth_zoo>=2026.4.8 (from unsloth)
  Downloading unsloth_zoo-2026.4.8-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.46.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth) (26.0)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.25.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Collecting tyro (from unsloth)
  Downloading tyro-1.0.13-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.6)
Collecting xformers>=0.0.27.post2 (from unsloth)
  Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Collecting bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 (from unsloth)
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.6.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Collecting datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 (from unsloth)
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.10.1)
Collecting hf_transfer (from unsloth)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.37.1)
Collecting transformers
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Collecting trl!=0.19.0,<=0.24.0,>=0.18.2 (from unsloth)
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.24.1)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.12.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from unsloth) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.6.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft) (0.7.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.2)
Collecting pyarrow>=21.0.0 (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth)
  Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth) (1.4.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Collecting torchao>=0.13.0 (from unsloth_zoo>=2026.4.8->unsloth)
  Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Collecting cut_cross_entropy (from unsloth_zoo>=2026.4.8->unsloth)
  Downloading cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2026.4.8->unsloth) (11.3.0)
Collecting msgspec (from unsloth_zoo>=2026.4.8->unsloth)
  Downloading msgspec-0.21.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->unsloth) (0.4.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->unsloth) (0.0.4)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (0.17.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.5.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.13.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->unsloth) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->unsloth) (2.20.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata->diffusers->unsloth) (3.23.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->unsloth) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.17.0)
Downloading unsloth-2026.4.6-py3-none-any.whl (65.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.3/65.3 MB 14.3 MB/s eta 0:00:00
Downloading transformers-5.5.0-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 60.4 MB/s eta 0:00:00
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 11.0 MB/s eta 0:00:00
Downloading datasets-4.3.0-py3-none-any.whl (506 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 37.3 MB/s eta 0:00:00
Downloading trl-0.24.0-py3-none-any.whl (423 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 23.5 MB/s eta 0:00:00
Downloading unsloth_zoo-2026.4.8-py3-none-any.whl (421 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 421.2/421.2 kB 36.8 MB/s eta 0:00:00
Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 78.1 MB/s eta 0:00:00
Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 74.6 MB/s eta 0:00:00
Downloading tyro-1.0.13-py3-none-any.whl (185 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.2/185.2 kB 16.0 MB/s eta 0:00:00
Downloading pyarrow-23.0.1-cp312-cp312-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 14.2 MB/s eta 0:00:00
Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 62.1 MB/s eta 0:00:00
Downloading cut_cross_entropy-25.1.1-py3-none-any.whl (22 kB)
Downloading msgspec-0.21.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (225 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.0/225.0 kB 28.8 MB/s eta 0:00:00
Installing collected packages: torchao, pyarrow, msgspec, hf_transfer, tyro, xformers, cut_cross_entropy, bitsandbytes, datasets, transformers, trl, unsloth_zoo, unsloth
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed bitsandbytes-0.49.2 cut_cross_entropy-25.1.1 datasets-4.3.0 hf_transfer-0.1.9 msgspec-0.21.1 pyarrow-23.0.1 torchao-0.17.0 transformers-5.5.0 trl-0.24.0 tyro-1.0.13 unsloth-2026.4.6 unsloth_zoo-2026.4.8 xformers-0.0.35

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# import unsloth
# from unsloth import FastLanguageModel
# from peft import PeftModel

# # 1️⃣ Load base model
# model, tokenizer = FastLanguageModel.from_pretrained(
#     "unsloth/Qwen2.5-7B",
#     # max_seq_length = 4096,
#     load_in_4bit=True
# )

# # 2️⃣ Load LoRA adapter from HF Hub
# model = PeftModel.from_pretrained(
#     model,
#     "nirasha/qwen2.5-7b-fact-inclusion-lora-v6"
# )

# # model.eval()

==((====))==  Unsloth 2026.2.1: Fast Qwen2 patching. Transformers: 4.57.6.
   \\   /|    NVIDIA L4. Num GPUs = 1. Max memory: 22.034 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
checkpoint_path = "/content/drive/MyDrive/research/models/qwen3_15_02_26/outputs/checkpoint-300"

In [ ]:
import unsloth
from unsloth import FastLanguageModel
from peft import PeftModel

# Load base model
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen3-8B",
    max_seq_length = 4096,
    load_in_4bit=True
)
model = PeftModel.from_pretrained(model, checkpoint_path)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.4.6: Fast Qwen3 patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/399 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/237 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

unsloth/qwen3-8b-unsloth-bnb-4bit does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.

In [ ]:
model.to("cuda")
model.eval()

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen3ForCausalLM(
      (model): Qwen3Model(
        (embed_tokens): Embedding(151936, 4096, padding_idx=151669)
        (layers): ModuleList(
          (0-2): 3 x Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=12288, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=12288, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=12288, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=12288, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear(
                (base_layer): Linear(in_features=12288, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=12288, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLUActivation()
            )
            (input_layernorm): Qwen3RMSNorm((4096,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((4096,), eps=1e-06)
          )
          (3): Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=12288, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=12288, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=12288, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=12288, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=12288, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=12288, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLUActivation()
            )
            (input_layernorm): Qwen3RMSNorm((4096,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((4096,), eps=1e-06)
          )
          (4): Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=12288, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=12288, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=12288, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=12288, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear(
                (base_layer): Linear(in_features=12288, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=12288, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLUActivation()
            )
            (input_layernorm): Qwen3RMSNorm((4096,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((4096,), eps=1e-06)
          )
          (5): Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=12288, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=12288, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=12288, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )

In [ ]:
# import torch
# import json

# def alpaca_inference(model, tokenizer, instruction, input_text="", max_tokens=2048, temperature=0.1):
#     """
#     Generate an Alpaca-style response.

#     Args:
#         model: Loaded PEFT model
#         tokenizer: Tokenizer
#         instruction (str): Instruction text
#         input_text (str): Optional input
#         max_tokens (int): Max tokens to generate
#         temperature (float): The temperature for text generation. A lower value makes the output more deterministic.

#     Returns:
#         str: Model response
#     """
#     prompt = f"""Below is an instruction that describes a task. Write a response that appropriately completes the request.

# ### Instruction:
# {instruction}

# ### Input:
# {input_text}

# ### Response:
# """

#     inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

#     with torch.no_grad():
#         outputs = model.generate(**inputs, max_new_tokens=max_tokens, temperature=temperature)

#     return tokenizer.decode(outputs[0], skip_special_tokens=True).replace(prompt, "").strip()

In [ ]:
instruction = """
Given detailed Text Triplets and Summary Triplets, identify supporting evidence paths that justify each summary triple. Think step-by-step and show your reasoning chain.

Algorithm:
(1) Create the knowledge graph using Text Triplets.
(2) For the given summary triplet, identify the two entities and the relation between them.
(3) For each entity in the summary triplet, create a mapper for the possible entities in the knowledge graph.
(4) For each summary triplet, traverse the constructed knowledge graph and identify supporting paths. Use the previously created mapper to resolve the entities. Perform multi-hopping if needed.
(5) When there is no match, return a emtpy list as evidence paths

Confidence Scale:
- 2 → Direct support: explicit edge or near-direct path exists in the KG
- 1 → Inferential support: implied through multi-hop traversal or categorical abstraction from multiple triplets
- 0 → Unsupported: no meaningful path found

Guidelines:
- If no Text Triplets support a Summary Triplet, set "is_supported": false and confidence:0
- In reasoning, explain either the connection OR why no connection exists
- Resolve the entities and relations if there are synonyms or variations
- Be strict: only mark as supported if there's clear evidence
- Consider summary triplets can be abstacted compared with the text triplets

Please only return a JSON with this structure: { "summary_triple": ["entity1", "relation", "entity2"], "is_supported": true/false, "supporting_evidence": [list of relevant Text Triplets] or [list of max 3 relevant but insufficient Text Triplets if unsupported], "confidence": 0-2 (only if supported, 0 otherwise), "reasoning": "Explain the explicit graph-based derivation OR clearly state which link is missing" }
"""

In [ ]:
instruction = """
Given detailed Text Triplets and Summary Triplets, identify supporting evidence paths that justify each summary triple. Think step-by-step and show your reasoning chain.

Algorithm:
(1) Create the knowledge graph using Text Triplets.
(2) For the given summary triplet, identify the two entities and the relation between them.
(3) For each entity in the summary triplet, create a mapper for the possible entities in the knowledge graph.
(4) For each summary triplet, traverse the constructed knowledge graph and identify supporting paths. Use the previously created mapper to resolve the entities. Perform multi-hopping if needed.
(5) When there is no match, identify the Text Triplets where no match occurs. Record the triplets in the text where no match occurs.

Confidence Scale:
- 2 → Direct support: explicit edge or near-direct path exists in the KG
- 1 → Inferential support: implied through multi-hop traversal or categorical abstraction from multiple triplets
- 0 → Unsupported: no meaningful path found

Guidelines:
- If no Text Triplets support a Summary Triplet, set "is_supported": false and confidence:0
- In reasoning, explain either the connection OR why no connection exists
- Resolve the entities and relations if there are synonyms or variations
- Be strict: only mark as supported if there's clear evidence
- Consider summary triplets can be abstacted compared with the text triplets

Please only return a JSON with this structure: { "summary_triple": ["entity1", "relation", "entity2"], "is_supported": true/false, "supporting_evidence": [list of relevant Text Triplets], "confidence": 0-2 (only if supported, 0 otherwise), "reasoning": "Explain the explicit graph-based derivation OR clearly state which link is missing" }
"""

- Be strict: only mark as supported if there's clear evidence

In [ ]:
insttruction_short = """
Given detailed Text Triplets and Summary Triplets, identify supporting evidence paths that justify each summary triple. Think step-by-step and show your reasoning chain.

Confidence Scale:
- 2 → Direct support: explicit edge or near-direct path exists in the KG
- 1 → Inferential support: implied through multi-hop traversal or categorical abstraction from multiple triplets
- 0 → Unsupported: no meaningful path found

Guidelines:
- If no Text Triplets support a Summary Triplet, set "is_supported": false and confidence:0
- In reasoning, explain either the connection OR why no connection exists
- Resolve the entities and relations if there are synonyms or variations
- Be strict: only mark as supported if there's clear evidence
- Consider summary triplets can be abstacted compared with the text triplets

Please only return a JSON with this structure: { "summary_triple": ["entity1", "relation", "entity2"], "is_supported": true/false, "supporting_evidence": [list of relevant Text Triplets] or [list of max 3 relevant but insufficient Text Triplets if unsupported], "confidence": 0-2 (only if supported, 0 otherwise), "reasoning": "Explain the explicit graph-based derivation OR clearly state which link is missing" }
"""

In [ ]:
instruction = """
Given detailed Text Triplets and Summary Triplets, identify supporting evidence paths that justify each summary triple. Think step-by-step and show your reasoning chain.

Algorithm:
(1) Create the knowledge graph using Text Triplets.
(2) For the given summary triplet, identify the two entities and the relation between them.
(3) For each entity in the summary triplet, create a mapper for the possible entities in the knowledge graph.
(4) For each summary triplet, traverse the constructed knowledge graph and identify supporting paths. Use the previously created mapper to resolve the entities. Perform multi-hopping if needed.
(5) When there is no match, identify the Text Triplets where no match occurs. Record the triplets in the text where no match occurs.

Confidence Scale:
Confidence 2 criteria:
- The summary relation is explicitly stated in a source triplet with matching or near-matching entities (1 hop)
- OR the same fact is expressed with minor surface variation but no logical inference required (synonym/paraphrase)
Confidence 1 criteria:
- The fact requires chaining 2+ source triplets
- OR the fact represents categorical abstraction (e.g. "is a Paralympic athlete" derived from competition evidence)
- OR logical inference is required beyond what is explicitly stated
Confidence 0 criteria:
- No path exists in source KG
- OR only generic "related to" edges connect the entities with no meaningful relation

Guidelines:
- If no Text Triplets support a Summary Triplet, set "is_supported": false and confidence:0
- In reasoning, explain either the connection OR why no connection exists
- Resolve the entities and relations if there are synonyms or variations
- Be strict: only mark as supported if there's clear evidence
- Consider summary triplets can be abstacted compared with the text triplets

Please only return a JSON with this structure: { "summary_triple": ["entity1", "relation", "entity2"], "is_supported": true/false, "supporting_evidence": [list of relevant Text Triplets] or [list of max 3 relevant but insufficient Text Triplets if unsupported], "confidence": 0-2 (only if supported, 0 otherwise), "reasoning": "Explain the explicit graph-based derivation OR clearly state which link is missing" }
"""

###New

In [ ]:
import torch
import json
import re

# The standard Qwen3 ChatML format
qwen3_prompt = """<|im_start|>system
You are a helpful assistant that reasons step-by-step.<|im_end|>
<|im_start|>user
{instruction}

{input}<|im_end|>
<|im_start|>assistant
<|think|>
"""

@torch.no_grad()
def alpaca_inference(
    model,
    tokenizer,
    instruction: str,
    input_text: str,
    temperature: float = 0.1
):

    prompt = qwen3_prompt.format(instruction=instruction, input=input_text)

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        add_special_tokens=False
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=4096,
        temperature=0.1,
        top_p=0.95,
        do_sample=(temperature > 0),
        repetition_penalty=1.15,      # Prevents infinite loops/digits
        # no_repeat_ngram_size=4,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.eos_token_id,
        use_cache=True,
    )

    # 1. Decode the full sequence
    full_text = tokenizer.decode(outputs[0], skip_special_tokens=False)
    return full_text

    # # 2. Extract everything after the assistant start tag
    # # This removes the System and User blocks
    # if "<|im_start|>assistant" in full_text:
    #     assistant_part = full_text.split("<|im_start|>assistant")[-1]
    # else:
    #     assistant_part = full_text

    # # 3. Remove the thinking process (everything inside <|think|>)
    # # We look for the closing </think> tag
    # if "</think>" in assistant_part:
    #     final_response = assistant_part.split("</think>")[-1]
    # else:
    #     final_response = assistant_part

    # # 4. Clean up any remaining ChatML tags (like <|im_end|>)
    # final_response = final_response.replace("<|im_end|>", "").strip()

    # return final_response

In [ ]:
def verify_triplet_inference(model, tokenizer, document_triplets, summary_triple):

    input_text = (
        f"Text triplets: {json.dumps(document_triplets, ensure_ascii=False)}\n\n"
        f"Summary triple: {json.dumps(summary_triple, ensure_ascii=False)}"
    )

    response = alpaca_inference(
        model,
        tokenizer,
        instruction,
        input_text
    )



    # # 🔹 Extract JSON safely
    # match = re.search(r"\{.*\}", response, re.DOTALL)
    # if not match:
    #     raise ValueError("No valid JSON found in model output.")

    # return match.group()

    return response

In [ ]:
temp_inst = "Verify the summary triple against the text triplets"

In [ ]:
# instruction = "Given a document with text triplets and a summary triple, determine if the summary triple is supported by the document's text triplets. Construct the knowledge graph and traverse it to find supporting evidence. Resolve entities where necessary. Provide a detailed response in JSON format with fields: summary_triple, is_supported, supporting_evidence, confidence, and reasoning."
text_triplets = [
      ["Officers", "searched", "properties"],
      ["properties", "located in", "Waterfront Park"],
      ["properties", "located in", "Colonsay View areas"],
      ["Waterfront Park", "part of", "the city"],
      ["Colonsay View areas", "part of", "the city"],
      ["Officers", "conducted search on", "Wednesday"],
      ["Detectives", "recovered", "three firearms"],
      ["Detectives", "recovered", "ammunition"],
      ["Detectives", "recovered", "five-figure sum of money"],
      ["26-year-old man", "was arrested by", "Officers"],
      ["26-year-old man", "was charged by", "Officers"],
      ["26-year-old man", "appeared at", "Edinburgh Sheriff Court"],
      ["26-year-old man", "appeared on", "Thursday"],
      ["Edinburgh Sheriff Court", "associated with", "Thursday"]
    ]
summary_triple = ["man", "associated with", "firearms"]

response = verify_triplet_inference(model, tokenizer, text_triplets, summary_triple)

# Ensure GPU finishes work
torch.cuda.synchronize()

# Optional: free cached memory
torch.cuda.empty_cache()

# parsed_response = json.loads(response)
# pretty_json = json.dumps(parsed_response, indent=4)
# print(pretty_json)
print(response)

Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

<|im_start|>system
You are a helpful assistant that reasons step-by-step.<|im_end|>
<|im_start|>user

Given detailed Text Triplets and Summary Triplets, identify supporting evidence paths that justify each summary triple. Think step-by-step and show your reasoning chain.

Algorithm:
(1) Create the knowledge graph using Text Triplets.
(2) For the given summary triplet, identify the two entities and the relation between them.
(3) For each entity in the summary triplet, create a mapper for the possible entities in the knowledge graph.
(4) For each summary triplet, traverse the constructed knowledge graph and identify supporting paths. Use the previously created mapper to resolve the entities. Perform multi-hopping if needed.
(5) When there is no match, return a emtpy list as evidence paths

Confidence Scale:
- 2 → Direct support: explicit edge or near-direct path exists in the KG
- 1 → Inferential support: implied through multi-hop traversal or categorical abstraction from multiple triplets
- 0 → Unsupported: no meaningful path found

Guidelines:
- If no Text Triplets support a Summary Triplet, set "is_supported": false and confidence:0
- In reasoning, explain either the connection OR why no connection exists
- Resolve the entities and relations if there are synonyms or variations
- Be strict: only mark as supported if there's clear evidence
- Consider summary triplets can be abstacted compared with the text triplets

Please only return a JSON with this structure: { "summary_triple": ["entity1", "relation", "entity2"], "is_supported": true/false, "supporting_evidence": [list of relevant Text Triplets] or [list of max 3 relevant but insufficient Text Triplets if unsupported], "confidence": 0-2 (only if supported, 0 otherwise), "reasoning": "Explain the explicit graph-based derivation OR clearly state which link is missing" }


Text triplets: [["Officers", "searched", "properties"], ["properties", "located in", "Waterfront Park"], ["properties", "located in", "Colonsay View areas"], ["Waterfront Park", "part of", "the city"], ["Colonsay View areas", "part of", "the city"], ["Officers", "conducted search on", "Wednesday"], ["Detectives", "recovered", "three firearms"], ["Detectives", "recovered", "ammunition"], ["Detectives", "recovered", "five-figure sum of money"], ["26-year-old man", "was arrested by", "Officers"], ["26-year-old man", "was charged by", "Officers"], ["26-year-old man", "appeared at", "Edinburgh Sheriff Court"], ["26-year-old man", "appeared on", "Thursday"], ["Edinburgh Sheriff Court", "associated with", "Thursday"]]

Summary triple: ["man", "associated with", "firearms"]<|im_end|>
<|im_start|>assistant
<|think|>
</think>

{"summary_triple": ["man", "associated with", "firearms"], "is_supported": true, "supporting_evidence": [["Detectives", "recovered", "three firearms"], ["26-year-old man", "was arrested by", "Officers"], ["26-year-old man", "was charged by", "Officers"]], "confidence": 1, "reasoning": "Multi-hop inference: The man was arrested/charged by officers who recovered firearms."}<|im_end|>

In [ ]:
print(response)

{'summary_triple': ['charity', 'operates in', 'Wales'], 'is_supported': False, 'supporting_evidence': [['Prison Link Cymru', 'operates in', '2015-16'], ['Prison Link Cymru', 'helps people find', 'accommodation'], ['Emmaus', 'provides', 'safe environment'], ['Housing Act', 'introduced in', '2015']], 'confidence': 1, 'reasoning': "The entity 'charity' is not explicitly defined in the document, and while 'Prison Link Cymru' and 'Emmaus' are charities, there is no direct evidence that either charity operates specifically in Wales."}

In [ ]:
# Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
# <|im_start|>system
# You are a helpful assistant that reasons step-by-step.<|im_end|>
# <|im_start|>user

# Given detailed Text Triplets and Summary Triplets, identify supporting evidence paths that justify each summary triple. Think step-by-step and show your reasoning chain.

# Algorithm:
# (1) Create the knowledge graph using Text Triplets.
# (2) For the given summary triplet, identify the two entities and the relation between them.
# (3) For each entity in the summary triplet, create a mapper for the possible entities in the knowledge graph.
# (4) For each summary triplet, traverse the constructed knowledge graph and identify supporting paths. Use the previously created mapper to resolve the entities. Perform multi-hopping if needed.
# (5) When there is no match, return a emtpy list as evidence paths

# Confidence Scale:
# - 2 → Direct support: explicit edge or near-direct path exists in the KG
# - 1 → Inferential support: implied through multi-hop traversal or categorical abstraction from multiple triplets
# - 0 → Unsupported: no meaningful path found

# Guidelines:
# - If no Text Triplets support a Summary Triplet, set "is_supported": false and confidence:0
# - In reasoning, explain either the connection OR why no connection exists
# - Resolve the entities and relations if there are synonyms or variations
# - Be strict: only mark as supported if there's clear evidence
# - Consider summary triplets can be abstacted compared with the text triplets

# Please only return a JSON with this structure: { "summary_triple": ["entity1", "relation", "entity2"], "is_supported": true/false, "supporting_evidence": [list of relevant Text Triplets] or [list of max 3 relevant but insufficient Text Triplets if unsupported], "confidence": 0-2 (only if supported, 0 otherwise), "reasoning": "Explain the explicit graph-based derivation OR clearly state which link is missing" }


# Text triplets: [["Officers", "searched", "properties"], ["properties", "located in", "Waterfront Park"], ["properties", "located in", "Colonsay View areas"], ["Waterfront Park", "part of", "the city"], ["Colonsay View areas", "part of", "the city"], ["Officers", "conducted search on", "Wednesday"], ["Detectives", "recovered", "three firearms"], ["Detectives", "recovered", "ammunition"], ["Detectives", "recovered", "five-figure sum of money"], ["26-year-old man", "was arrested by", "Officers"], ["26-year-old man", "was charged by", "Officers"], ["26-year-old man", "appeared at", "Edinburgh Sheriff Court"], ["26-year-old man", "appeared on", "Thursday"], ["Edinburgh Sheriff Court", "associated with", "Thursday"]]

# Summary triple: ["man", "associated with", "firearms"]<|im_end|>
# <|im_start|>assistant
# <|thought|>
# Okay, let me work through this step by step. The user wants to know if the summary triplet ["man", "associated with", "firearms"] is supported by the provided Text Triplets.

# First, I need to parse the Text Triplets and build the knowledge graph. Let's look at the entities involved here: "man", "firearms", and the association relation.

# Looking at the Text Triplets, I see that "Detectives" recovered "three firearms". But where does "man" come into play? There's mention of a "26-year-old man who was arrested by Officers and was charged by Officers." So the man was arrested and charged, but does he have any direct connection to the firearms?

# Wait, the Text Triplets don't explicitly say that the man had contact with the firearms. He was arrested by officers, but the firearms were recovered by detectives. Unless there's an implicit assumption that since he was arrested during searches related to these items, he might be associated with them. However, based strictly on the Text Triplets provided, there's no explicit statement linking the man directly to the firearms. The connection would require inference beyond what's stated.

# So while it's plausible that the man could be connected to the firearms due to his arrest, the Text Triplets themselves do not provide explicit evidence of this association. Therefore, the summary triplet isn't directly supported by the available Text Triplets.
# </think>

# {"summary_triple": ["man", "associated with", "firearms"], "is_supported": false, "supporting_evidence": [["Detectives", "recovered", "three firearms"], ["26-year-old man", "was arrested by", "Officers"]], "confidence": 0, "reasoning": "No explicit textual connection shows the man being 'associated with' firearms; the firearms recovery and man's arrest occur independently without establishing their relationship"}<|im_end|>

In [ ]:
# Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
# <|im_start|>system
# You are a helpful assistant that reasons step-by-step.<|im_end|>
# <|im_start|>user

# Given detailed Text Triplets and Summary Triplets, identify supporting evidence paths that justify each summary triple. Think step-by-step and show your reasoning chain.

# Algorithm:
# (1) Create the knowledge graph using Text Triplets.
# (2) For the given summary triplet, identify the two entities and the relation between them.
# (3) For each entity in the summary triplet, create a mapper for the possible entities in the knowledge graph.
# (4) For each summary triplet, traverse the constructed knowledge graph and identify supporting paths. Use the previously created mapper to resolve the entities. Perform multi-hopping if needed.
# (5) When there is no match, return a emtpy list as evidence paths

# Confidence Scale:
# - 2 → Direct support: explicit edge or near-direct path exists in the KG
# - 1 → Inferential support: implied through multi-hop traversal or categorical abstraction from multiple triplets
# - 0 → Unsupported: no meaningful path found

# Guidelines:
# - If no Text Triplets support a Summary Triplet, set "is_supported": false and confidence:0
# - In reasoning, explain either the connection OR why no connection exists
# - Resolve the entities and relations if there are synonyms or variations
# - Be strict: only mark as supported if there's clear evidence
# - Consider summary triplets can be abstacted compared with the text triplets

# Please only return a JSON with this structure: { "summary_triple": ["entity1", "relation", "entity2"], "is_supported": true/false, "supporting_evidence": [list of relevant Text Triplets] or [list of max 3 relevant but insufficient Text Triplets if unsupported], "confidence": 0-2 (only if supported, 0 otherwise), "reasoning": "Explain the explicit graph-based derivation OR clearly state which link is missing" }


# Text triplets: [["Officers", "searched", "properties"], ["properties", "located in", "Waterfront Park"], ["properties", "located in", "Colonsay View areas"], ["Waterfront Park", "part of", "the city"], ["Colonsay View areas", "part of", "the city"], ["Officers", "conducted search on", "Wednesday"], ["Detectives", "recovered", "three firearms"], ["Detectives", "recovered", "ammunition"], ["Detectives", "recovered", "five-figure sum of money"], ["26-year-old man", "was arrested by", "Officers"], ["26-year-old man", "was charged by", "Officers"], ["26-year-old man", "appeared at", "Edinburgh Sheriff Court"], ["26-year-old man", "appeared on", "Thursday"], ["Edinburgh Sheriff Court", "associated with", "Thursday"]]

# Summary triple: ["police", "seized", "firearms"]<|im_end|>
# <|im_start|>assistant
# <|thought|>
# Okay, let me work through this step by step. The user wants to know if the summary triplet ["police", "seized", "firearms"] is supported by the provided Text Triplets.

# First, I need to map the entities. "Police" corresponds to "Officers" in the Text Triplets. "Seized" would translate to "recovered" since that's what happened with the items mentioned. And "firearms" should correspond to "three firearms".

# Looking at the Text Triplets, I see that Detectives recovered three firearms. But wait, the summary mentions police ("Officers") instead of detectives. Are Officers considered police? That might depend on context, but assuming they're equivalent here.

# So the key points are: Officers (as police) recovering firearms. The Text Triplet says Detectives recovered three firearms. Since both officers and detectives are law enforcement personnel, it's reasonable to consider them as police in this context. Therefore, the seizure action aligns with the recovery described.

# I think that covers the necessary connections. Let me check again to make sure there's no missing piece.
# </s>

# {"summary_triple": ["police", "seized", "firearms"], "is_supported": true, "supporting_evidence": [["Detectives", "recovered", "three firearms"]], "confidence": 2, "reasoning": "Direct mapping: 'police' = 'Officers/Detectives', 'seized/firearms' = 'recovered/three firearms'. Both entities exist explicitly."}<|im_end|>

# For batch processing

In [ ]:
import pandas as pd

data_path = "/content/drive/MyDrive/research/data/inferencing/lora_inference/14-02-26/expanded_triplet_evaluations_3.csv"
# data_path = "/content/drive/MyDrive/research/data/inferencing/triplet_generation/gpt_oss_120b/expanded_triplets_gpt_oss.csv"
data_df = pd.read_csv(data_path)
data_df.tail()

,doc_id,document,summary,generated_summary,document_triplets,gen_summary_triplets,summary_triplet_subject,summary_triplet_predicate,summary_triplet_object,summary_triplet_full,is_supported,confidence,reasoning,supporting_evidence
618,35844158,"Omar Khan, 31, had worked at The Johnson Partn...",A barrister who was due to move into his own c...,A solicitor has admitted conspiring to supply ...,"[['Omar Khan', 'worked at', 'The Johnson Partn...","[['solicitor', 'admitted', 'conspiring to supp...",solicitor,admitted,conspiring to supply cocaine,"['solicitor', 'admitted', 'conspiring to suppl...",True,2,Omar Khan is identified as a solicitor through...,"[['Omar Khan', 'admitted', 'conspiracy to supp..."
619,35844158,"Omar Khan, 31, had worked at The Johnson Partn...",A barrister who was due to move into his own c...,A solicitor has admitted conspiring to supply ...,"[['Omar Khan', 'worked at', 'The Johnson Partn...","[['solicitor', 'admitted', 'conspiring to supp...",solicitor,conspired with,three other men,"['solicitor', 'conspired with', 'three other m...",True,2,"The three men (Erlin Manahasa, Albert Dibra, N...","[['Erlin Manahasa', 'joined', 'Omar Khan'], ['..."
620,35844158,"Omar Khan, 31, had worked at The Johnson Partn...",A barrister who was due to move into his own c...,A solicitor has admitted conspiring to supply ...,"[['Omar Khan', 'worked at', 'The Johnson Partn...","[['solicitor', 'admitted', 'conspiring to supp...",three other men,involved in,conspiring to supply cocaine,"['three other men', 'involved in', 'conspiring...",True,2,"All three men (Erlin Manahasa, Albert Dibra, N...","[['Erlin Manahasa', 'admitted charge at', 'Not..."
621,35844158,"Omar Khan, 31, had worked at The Johnson Partn...",A barrister who was due to move into his own c...,A solicitor has admitted conspiring to supply ...,"[['Omar Khan', 'worked at', 'The Johnson Partn...","[['solicitor', 'admitted', 'conspiring to supp...",conspiring to supply cocaine,involves,three other men,"['conspiring to supply cocaine', 'involves', '...",True,2,The conspiracy to supply cocaine (Class A drug...,"[['Erlin Manahasa', 'joined', 'Omar Khan'], ['..."
622,35844158,"Omar Khan, 31, had worked at The Johnson Partn...",A barrister who was due to move into his own c...,A solicitor has admitted conspiring to supply ...,"[['Omar Khan', 'worked at', 'The Johnson Partn...","[['solicitor', 'admitted', 'conspiring to supp...",solicitor,associated with,three other men,"['solicitor', 'associated with', 'three other ...",True,2,Omar Khan (the solicitor) is clearly associate...,"[['Erlin Manahasa', 'joined', 'Omar Khan'], ['..."

In [ ]:
len(data_df)

623

In [ ]:
fact_eval_res = []

In [ ]:
set_df = data_df[600:]

In [ ]:
from tqdm.auto import tqdm
import time
import torch
import json

for idx, row in tqdm(data_df.iterrows(), total=len(data_df)):
    text_triplets = row['document_triplets']
    summary_triple = row['summary_triplet_full']

    response = verify_triplet_inference(
        model, tokenizer, text_triplets, summary_triple
    )

    fact_eval_res.append(response)

    # Ensure GPU finishes work
    torch.cuda.synchronize()

    # Optional: free cached memory
    torch.cuda.empty_cache()

    # Rate limiting / pacing (not model stress)
    # time.sleep(1)

    if idx % 100 == 0:
      with open(f"/content/drive/MyDrive/research/data/inferencing/lora_inference/qwen3/14-04-26/fact_eval_res_{idx}.json", "w") as f:
        json.dump(fact_eval_res, f)

  0%|          | 0/623 [00:00<?, ?it/s]

Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=4096) and `max_length`(=40960) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [ ]:
for item in fact_eval_res[600:]:
    print(item)

{"summary_triple": ["patients", "located on", "mental health ward"], "is_supported": true, "supporting_evidence": [["Tawel Fan ward", "treated patients like", "animals"]], "confidence": 2, "reasoning": "Direct support: The treatment description implies these were mental health patients located on Tawel Fan ward."}
{"summary_triple": ["mental health ward", "described as", "troubled"], "is_supported": false, "supporting_evidence": [["Tawel Fan ward", "treated patients like", "animals"]], "confidence": 0, "reasoning": "No direct mention of 'mental health ward' or any description indicating it was 'troubled'. The closest reference is Tawel Fan ward treated patients poorly."}
{"summary_triple": ["loved ones", "may have died because of", "poor care"], "is_supported": true, "supporting_evidence": [["health care problems", "may have contributed to", "patient death"]], "confidence": 2, "reasoning": "Direct support: Explicit edge shows health care problems may have contributed to patient death."}
{"summary_triple": ["Families", "related to", "loved ones"], "is_supported": true, "supporting_evidence": [["seven patients' families", "told about", "treatment contribution to deaths"]], "confidence": 2, "reasoning": "Direct support: The Text Triplet shows seven patients' families were told about treatment contributions to deaths, establishing a relationship between families and loved ones."}
{"summary_triple": ["patients", "same as", "loved ones"], "is_supported": true, "supporting_evidence": [["seven patients' families", "told about", "treatment contribution to deaths"]], "confidence": 2, "reasoning": "The semantic equivalence is established by the fact that seven patients' families were told about treatment contributing to deaths - this implies that these patients had loved ones who cared about their treatment."}
{"summary_triple": ["poor care", "associated with", "mental health ward"], "is_supported": true, "supporting_evidence": [["Tawel Fan ward", "treated patients like animals"]], "confidence": 2, "reasoning": "Direct support: The treatment of patients like animals explicitly indicates poor care associated with Tawel Fan ward."}
{"summary_triple": ["25-year-old man", "from", "Limavady"], "is_supported": true, "supporting_evidence": [["Declan Paul Butcher", "appears at", "Londonderry Crown Court"]], "confidence": 1, "reasoning": "No direct evidence shows Declan Paul Butcher was from Limavady."}
{"summary_triple": ["25-year-old man", "from", "County Londonderry"], "is_supported": true, "supporting_evidence": [["Declan Paul Butcher", "appears at", "Londonderry Crown Court"]], "confidence": 2, "reasoning": "Direct support: Declan Paul Butcher appears at Londonderry Crown Court, establishing his location relationship"}
{"summary_triple": ["25-year-old man", "jailed for", "assaulting"], "is_supported": true, "supporting_evidence": [["Declan Paul Butcher", "sentenced to", "14 months in prison"]], "confidence": 2, "reasoning": "Direct support: Declan Paul Butcher was sentenced to jail time after committing assaults"}
{"summary_triple": ["25-year-old man", "assaulted", "two men"], "is_supported": true, "supporting_evidence": [["Declan Paul Butcher", "committed", "single punch assaults"]], "confidence": 2, "reasoning": "Direct support: Declan Paul Butcher committed single punch assaults"}
{"summary_triple": ["Limavady", "located in", "County Londonderry"], "is_supported": true, "supporting_evidence": [["Market Street", "located in", "Limavady"]], "confidence": 2, "reasoning": "Direct support: The Text Triplet explicitly states Market Street is located in Limavady, establishing Limavady as a location within County Londonderry."}
{"summary_triple": ["assaulting", "involves", "two men"], "is_supported": true, "supporting_evidence": [["Declan Paul Butcher", "committed", "single punch assaults"], ["Declan Paul Butcher", "knocked unconscious", "first victim"], ["second man", "suffered", "double jaw fracture"]], "confidence": 2, "reasoning": "Direct support: Explicit edges exist showing Declan Paul Butcher committed single punch assaults involving knocking out first victim and second man suffering double jaw fracture."}
{"summary_triple": ["Hope Solo", "is", "United States goalkeeper"], "is_supported": true, "supporting_evidence": [["Hope Solo", "won", "second Olympic gold medal"], ["Hope Solo", "won", "Olympic silver"], ["Hope Solo", "won", "World Cup titles"]], "confidence": 2, "reasoning": "Explicit direct support - Hope Solo has won international medals (Olympic gold/silver, World Cups), which categorically identifies her as a United States goalkeeper."}
{"summary_triple": ["Hope Solo", "suspended for", "two internationals"], "is_supported": true, "supporting_evidence": [["Hope Solo", "will miss", "matches on 8 February"], ["Hope Solo", "will miss", "matches on 13 February"]], "confidence": 2, "reasoning": "Explicit direct support: Hope Solo will miss matches on both dates, indicating suspension across these international matches."}
{"summary_triple": ["Hope Solo", "arrested for", "driving under the influence"], "is_supported": true, "supporting_evidence": [["Jerramy Stevens", "was arrested for", "driving under the influence"]], "confidence": 1, "reasoning": "The arrest was explicitly stated for driving under the influence, though it was Jerramy Stevens who was arrested."}
{"summary_triple": ["United States", "has goalkeeper", "Hope Solo"], "is_supported": true, "supporting_evidence": [["US", "preparing for", "Women's World Cup"]], "confidence": 1, "reasoning": "The US preparing for Women's World Cup implies they have players, including Hope Solo who was part of their team."}
{"summary_triple": ["driving under the influence", "resulted in", "suspension"], "is_supported": false, "supporting_evidence": [["Jerramy Stevens", "was arrested for", "driving under the influence"]], "confidence": 0, "reasoning": "No direct connection established - while Jerramy Stevens was arrested for driving under the influence, there is no mention of suspension resulting from this arrest."}
{"summary_triple": ["two internationals", "related to", "suspension"], "is_supported": false, "supporting_evidence": [["Hope Solo", "missed", "matches on 8 February"], ["Hope Solo", "missed", "matches on 13 February"]], "confidence": 0, "reasoning": "No direct mention of suspension; while Hope Solo missed matches, there is no explicit reference to her being suspended."}
{"summary_triple": ["solicitor", "admitted", "conspiring to supply cocaine"], "is_supported": true, "supporting_evidence": [["Omar Khan", "admitted", "conspiracy to supply Class A drug"]], "confidence": 2, "reasoning": "Direct support: Omar Khan admitted conspiracy to supply Class A drug, and he was described as a solicitor."}
{"summary_triple": ["solicitor", "conspired with", "three other men"], "is_supported": true, "supporting_evidence": [["Omar Khan", "admitted", "conspiracy to supply Class A drug"], ["Erlin Manahasa", "admitted charge at", "Nottingham Crown Court"], ["Albert Dibra", "admitted charge at", "Nottingham Crown Court"], ["Nazaquat Ali", "admitted charge at", "Nottingham Crown Court"]], "confidence": 2, "reasoning": "Direct support: Omar Khan admitted conspiracy to supply Class A drug, while Erlin Manahasa, Albert Dibra, and Nazaquat Ali also admitted charges - these three others conspired with him"}
{"summary_triple": ["three other men", "involved in", "conspiring to supply cocaine"], "is_supported": true, "supporting_evidence": [["Erlin Manahasa", "admitted charge at", "Nottingham Crown Court"], ["Albert Dibra", "admitted charge at", "Nottingham Crown Court"], ["Nazaquat Ali", "admitted charge at", "Nottingham Crown Court"]], "confidence": 2, "reasoning": "Direct support: Explicit edges showing Erlin Manahasa, Albert Dibra, and Nazaquat Ali admitted charges at court"}
{"summary_triple": ["conspiring to supply cocaine", "involves", "three other men"], "is_supported": true, "supporting_evidence": [["Omar Khan", "admitted", "conspiracy to supply Class A drug"], ["Erlin Manahasa", "admitted charge at", "Nottingham Crown Court"], ["Albert Dibra", "admitted charge at", "Nottingham Crown Court"], ["Nazaquat Ali", "admitted charge at", "Nottingham Crown Court"]], "confidence": 2, "reasoning": "Direct support: Omar Khan admitted conspiracy to supply Class A drug, and three others (Erlin Manahasa, Albert Dibra, Nazaquat Ali) also admitted charges related to the same case."}
{"summary_triple": ["solicitor", "associated with", "three other men"], "is_supported": true, "supporting_evidence": [["Omar Khan", "worked at", "The Johnson Partnership"], ["Erlin Manahasa", "joined", "Omar Khan"], ["Albert Dibra", "joined", "Omar Khan"], ["Nazaquat Ali", "joined", "Omar Khan"]], "confidence": 2, "reasoning": "Multi-hop inference: Omar Khan worked at The Johnson Partnership (which could imply he was solicitor-like role). Three others joined him - these three were associated with him."}

In [ ]:
len(fact_eval_res)

623

In [ ]:
data_df['fact_eval_res_lora'] = fact_eval_res
merged_df = data_df
merged_df.head()

,doc_id,document,summary,generated_summary,document_triplets,gen_summary_triplets,summary_triplet_subject,summary_triplet_predicate,summary_triplet_object,summary_triplet_full,is_supported,confidence,reasoning,supporting_evidence,fact_eval_res_lora
0,38264402,"Prison Link Cymru had 1,099 referrals in 2015-...","There is a ""chronic"" need for more housing for...","More than 1,000 homeless people were referred ...","[['Prison Link Cymru', 'had', '1,099 referrals...","[['More than 1,000 homeless people', 'referred...","More than 1,000 homeless people",referred to,charity,"['More than 1,000 homeless people', 'referred ...",True,2,"Prison Link Cymru (charity) had 1,099 referral...","[['Prison Link Cymru', 'had', '1,099 referrals']]","{""summary_triple"": [""More than 1,000 homeless ..."
1,38264402,"Prison Link Cymru had 1,099 referrals in 2015-...","There is a ""chronic"" need for more housing for...","More than 1,000 homeless people were referred ...","[['Prison Link Cymru', 'had', '1,099 referrals...","[['More than 1,000 homeless people', 'referred...",charity,located in,Wales,"['charity', 'located in', 'Wales']",True,2,"Prison Link Cymru is the charity mentioned, an...","[['Prison Link Cymru', 'operates in', '2015-16...","{""summary_triple"": [""charity"", ""located in"", ""..."
2,38264402,"Prison Link Cymru had 1,099 referrals in 2015-...","There is a ""chronic"" need for more housing for...","More than 1,000 homeless people were referred ...","[['Prison Link Cymru', 'had', '1,099 referrals...","[['More than 1,000 homeless people', 'referred...",referral,occurred in,last year,"['referral', 'occurred in', 'last year']",True,2,"Prison Link Cymru had 1,099 referrals and oper...","[['Prison Link Cymru', 'operates in', '2015-16...","{""summary_triple"": [""referral"", ""occurred in"",..."
3,38264402,"Prison Link Cymru had 1,099 referrals in 2015-...","There is a ""chronic"" need for more housing for...","More than 1,000 homeless people were referred ...","[['Prison Link Cymru', 'had', '1,099 referrals...","[['More than 1,000 homeless people', 'referred...","More than 1,000 homeless people",associated with,Wales,"['More than 1,000 homeless people', 'associate...",True,2,"The 1,099 referrals to Prison Link Cymru (more...","[['Prison Link Cymru', 'had', '1,099 referrals...","{""summary_triple"": [""More than 1,000 homeless ..."
4,38264402,"Prison Link Cymru had 1,099 referrals in 2015-...","There is a ""chronic"" need for more housing for...","More than 1,000 homeless people were referred ...","[['Prison Link Cymru', 'had', '1,099 referrals...","[['More than 1,000 homeless people', 'referred...",charity,associated with,last year,"['charity', 'associated with', 'last year']",True,2,Prison Link Cymru (the charity) operates in 20...,"[['Prison Link Cymru', 'operates in', '2015-16...","{""summary_triple"": [""charity"", ""associated wit..."

In [ ]:
len(merged_df)

623

In [ ]:
new_df = pd.DataFrame({'fact_eval_res_lora': fact_eval_res})
merged_df = data_df.merge(new_df, left_index=True, right_index=True)
merged_df.head()

In [ ]:
# save the file as a csv
merged_df.to_csv("/content/drive/MyDrive/research/data/inferencing/lora_inference/qwen3/09-04-26/results_traversal_ck_300_t_01.csv", index=False)

In [ ]:
# Access the max sequence length from the config
max_seq_length = model.config.max_position_embeddings

print(f"The maximum sequence length is: {max_seq_length}")

The maximum sequence length is: 40960